### ISSUE TITLE
Add tests for VertexAIGeminiChatGenerator

### ISSUE THREAD

**Issue by Amnah199** [deepset-ai/haystack-core-integrations#1019]
**Is your feature request related to a problem? Please describe.**
At the moment, we don't have any tests for `VertexAIGeminiChatGenerator`, which poses the risk of undetected bugs in future.

**Describe the solution you'd like**
Similar unit tests as `VertexAIGeminiGenerator`.

**Describe alternatives you've considered**
Rely on manual testing.

**Comment by anakin87** [comment]
I also feel that the [`GoogleAIGeminiChatGenerator`](https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/google_ai/tests/generators/chat/test_chat_gemini.py) tests can be improved.

An example:
https://github.com/deepset-ai/haystack-core-integrations/blob/50352b95e0caeedeb5779eeec3b6a7bd79542d80/integrations/google_ai/tests/generators/chat/test_chat_gemini.py#L222-L225

Here, I think we should check the role and the format of the returned message.
