### ISSUE TITLE
doc: Update documentation of GoogleAI and VertexAI to show streaming example

### ISSUE THREAD

**Issue by Amnah199** [deepset-ai/haystack-core-integrations#1036]
**Is your feature request related to a problem? Please describe.**
The below four components now support `streaming_callback`, similar to the OpenAIGenerator. After their release, it would be beneficial to include an example of 'Streaming' in the documentation to demonstrate its usage.

- `VertexAIGeminiChatGenerator`
- `VertexAIGeminiGenerator`
- `GoogleAIGeminiChatGenerator`
- `GoogleAIGeminiGenerator`

**Describe the solution you'd like**
Add a separate example code for streaming, similar to the example provided for the OpenAIGenerator in the documentation:
[OpenAIGenerator Example](https://docs.haystack.deepset.ai/docs/openaigenerator).

**Comment by julian-risch** [comment]
Daria added a section about streaming to the docs of all generators that support streaming. For example this section https://docs.haystack.deepset.ai/docs/vertexaigeminichatgenerator#streaming points to https://docs.haystack.deepset.ai/docs/choosing-the-right-generator#streaming-support

And there is a new column in the overview for streaming support https://docs.haystack.deepset.ai/docs/generators

With all that being done, we can close this issue.
