### ISSUE TITLE
AstraDB delete_documents performs an unnecessary count

### ISSUE THREAD

**Issue by brendancicchi** [deepset-ai/haystack-core-integrations#1047]
https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/astra/src/haystack_integrations/document_stores/astra/document_store.py#L406-L427

In delete_documents, an unnecessary check is being done, which is performing a full count of the collection as a naive check to ensure the collection is not empty. This is an extremely expensive operation and not one that is necessary, as performing a delete on nonexisting documents is not harmful. In reality, the existing check does not actually check if the document exists or not anyway.

The count_documents check should be removed.

**Comment by julian-risch** [comment]
Thank you @brendancicchi for opening this issue. I can see that you already worked on a fix. Would you like to open a pull request and contribute the fix to Haystack? 🙂 You can find our contributing guidelines here: https://github.com/deepset-ai/haystack/blob/main/CONTRIBUTING.md#contribute-code

**Comment by brendancicchi** [comment]
@julian-risch Yes, I'll open a PR. Due to this test https://github.com/deepset-ai/haystack/blob/main/haystack/testing/document_store.py#L161C5-L163C61, it looks like I can't just change the logic to do the same on an empty collection as when no document_ids are deleted. So, instead, I'll grab any single document as a check for a non-empty collection, which will be much cheaper than the full count.
