### ISSUE TITLE
docs: better document Weaviate connection options

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#1060]
Our [docs](https://docs.haystack.deepset.ai/docs/weaviatedocumentstore#initialization) and [integration page](https://haystack.deepset.ai/integrations/weaviate-document-store) do not explain well the different options to use Weaviate.

The Authorization part of the docs is helpful, but having some simple code to start would help too.

---

We might do something like the following

**Embedded**
It's a temporary instance, similar to our `InMemoryDocumentStore`
```python
from haystack_integrations.document_stores.weaviate import WeaviateDocumentStore
from weaviate.embedded import EmbeddedOptions

document_store = WeaviateDocumentStore(embedded_options=EmbeddedOptions())
```

**Docker**
- copy the docker-compose.yml file available [here](https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/weaviate/docker-compose.yml)
- start the docker container: `docker compose up -d`

```python
from haystack_integrations.document_stores.weaviate import WeaviateDocumentStore

document_store = WeaviateDocumentStore(url="http://localhost:8080")
```

**Weaviate Cloud Service**
- create your Weaviate cluster

```python
from haystack_integrations.document_stores.weaviate import WeaviateDocumentStore, AuthApiKey
from haystack import Document

import os
os.environ["WEAVIATE_API_KEY"] = "YOUR-API-KEY"

auth_client_secret = AuthApiKey()

document_store = WeaviateDocumentStore(url="YOUR-WEAVIATE-URL",
    auth_client_secret=auth_client_secret)
```

**Comment by dfokina** [comment]
Hey @anakin87 @julian-risch I added the initialization options to the docs here: https://docs.haystack.deepset.ai/docs/weaviatedocumentstore#initialization
