### ISSUE TITLE
Langfuse integration breaking - new release neeeded

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-core-integrations#1079]
**Describe the bug**
The community have reported on discord that they're encountering errors due to the deprecated `ChatMessage.to_openai_format()` function which seems to have been fixed in [this commit](https://github.com/deepset-ai/haystack-core-integrations/commit/55c65af5ac338f0678537125d6fd0e92dfa689b6) but it may be worth testing this. 

[Here's the original PR for it](https://github.com/deepset-ai/haystack-core-integrations/pull/1001)

They are currently resolving it by pip installing this branch. :
`pip install -U git+https://github.com/deepset-ai/haystack-core-integrations.git@main#subdirectory=integrations/langfuse`

Looks like we may have to make a new release for the fix to be available in the package. 

PS: For more context, refer to [this Discord thread](https://discord.com/channels/993534733298450452/1283001991223836672) and the users Jibran and  LastRemote:

**Comment by vblagoje** [comment]
Fixed with new [langfuse-haystack](https://pypi.org/project/langfuse-haystack/0.3.0/) release. The fix was in place already but we forgot to cut a new release. Suggest closing @TuanaCelik
