### ISSUE TITLE
Improve docs about Metadata Filtering 

### ISSUE THREAD

**Issue by Amnah199** [deepset-ai/haystack-core-integrations#1081]
**Is your feature request related to a problem? Please describe.**
 The current documentation for Metadata Filtering lacks structure and is incomplete, making it difficult to understand. As we are also disabling legacy filters, our documentation should be clear.
https://docs.haystack.deepset.ai/docs/metadata-filtering

**Describe the solution you'd like:**
 The documentation should include a decent explanation of available filter keys and operators. We can also include clear examples covering specific use cases such as nested filters, to demonstrate the correct syntax and usage.

**Comment by dfokina** [comment]
https://docs.haystack.deepset.ai/docs/metadata-filtering
