### ISSUE TITLE
Chroma - defer the DB connection

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#1101]
In #1094, we introduced the possibility of connecting via HTTP to a Chroma server.

Previously, Chroma could only be run in-memory, within the same process as the Python script utilizing it.

This new option conflicts with the work done in #746 to avoid database connections in document stores constructors.

**We should refactor Chroma as we did for other Document Stores and only then release a new version.**

**Comment by alperkaya** [comment]
Hi,

I took the liberty of deferring the DB connection from Chroma.
LMK your comments. 

Thanks!
