### ISSUE TITLE
Support full parameter set for Ollama integrations  

### ISSUE THREAD

**Issue by emso-c** [deepset-ai/haystack-core-integrations#1129]
**Is your feature request related to a problem? Please describe.**

Ollama integrations do not support the full capabilities of the generation methods. Namely `OllamaGenerator.generate` and `OllamaChatGenerator.chat` methods. I was trying to add the keep_alive option to the generation using the OllamaGenerator. But when I inspected the [code](https://github.com/deepset-ai/haystack-core-integrations/blob/9438634f2082bc8c7ebd518f319512ed4fbe9882/integrations/ollama/src/haystack_integrations/components/generators/ollama/generator.py#L175), I've seen that the method only passed down the `model`, `prompt`, `stream` and `options` parameters, even though the Ollama client is capable of utilizing more:

```python
@overload
  def generate(
    self,
    model: str = '',
    prompt: str = '',
    suffix: str = '',
    system: str = '',
    template: str = '',
    context: Optional[Sequence[int]] = None,
    stream: Literal[True] = True,
    raw: bool = False,
    format: Literal['', 'json'] = '',
    images: Optional[Sequence[AnyStr]] = None,
    options: Optional[Options] = None,
    keep_alive: Optional[Union[float, str]] = None,
  ) -> Iterator[Mapping[str, Any]]: ...
```

**Describe the solution you'd like**
Adding all the top level parameters that ollama client is able to use to the `OllamaGenerator` and `OllamaChatGenerator` constructors respectively.

**Describe alternatives you've considered**
Using kwargs to pass down the parameters manually:

```python
class OllamaGenerator:
    def __init__(
        ...
        run_kwargs: Optional[Dict[str, Any]] = None # added line
    ) 
    ...
    def run(
        ...
        response = self._client.generate(model=self.model,
                                         prompt=prompt,
                                         stream=stream,
                                         options=generation_kwargs,
                                         **self.run_kwargs) # added line
        ...

# usage
generator = OllamaGenerator(
    run_kwargs={"keep_alive": "5m"},
)
```

**Additional context**

**Comment by anakin87** [comment]
Some of the available parameters are already supported.

**For now, I would only add support for `keep_alive`, which seems important.**

Feel free to create a PR if you want, otherwise we will take care of it in the future.

**Comment by anakin87** [comment]
Support for `keep_alive` was added in #1131.

Support for images will be added when we focus more on enabling multimodal use cases throughout the framework.
