### ISSUE TITLE
TypeError: LangfuseTracer.trace() got an unexpected keyword argument 'parent_span' 

### ISSUE THREAD

**Issue by schwasa** [deepset-ai/haystack-core-integrations#1174]
**Describe the bug**
I had a running Haystack pipeline that was using langfuse for tracing. However, all of the sudden I received an error "TypeError: LangfuseTracer.trace() got an unexpected keyword argument 'parent_span'". @marcklingen stated, that "Parent_span does not exist on a trace, which is correct". Here is a simple example of the code I am using:

**To Reproduce**
Example code:

```from haystack.document_stores.in_memory import InMemoryDocumentStore
from haystack.components.converters import PyPDFToDocument
from haystack.components.preprocessors import DocumentSplitter, DocumentCleaner
from haystack.components.writers import DocumentWriter
from haystack.components.embedders import SentenceTransformersDocumentEmbedder, SentenceTransformersTextEmbedder
from haystack.components.generators import HuggingFaceAPIGenerator
from haystack import Pipeline
from haystack_integrations.components.connectors.langfuse import LangfuseConnector

embedding_model = "sentence-transformers/all-MiniLM-L6-v2"

document_embedder = SentenceTransformersDocumentEmbedder(model=embedding_model)
query_embedder = SentenceTransformersTextEmbedder(model=embedding_model)

llm_generator = HuggingFaceAPIGenerator(
    api_type="serverless_inference_api",
    api_params={"model": "mistralai/Mistral-7B-Instruct-v0.3"},
    generation_kwargs={
        "temperature": 1,
    }
)

prompt_template = """Based on the following documents, answer the question:

{% for doc in documents %}
    {{ doc.content }}
{% endfor %}

Question: {{ query }}
Answer:"""

document_store = InMemoryDocumentStore()

pdf_converter = PyPDFToDocument()
document_cleaner = DocumentCleaner()
document_splitter = DocumentSplitter(split_by="sentence", split_length=5, split_overlap=0)
document_writer = DocumentWriter(document_store=document_store)

indexing_pipeline = Pipeline()
indexing_pipeline.add_component("tracer", LangfuseConnector("Simple Haystack Example"))
indexing_pipeline.add_component("pdf_converter", pdf_converter)
indexing_pipeline.add_component("document_cleaner", document_cleaner)
indexing_pipeline.add_component("document_splitter", document_splitter)
indexing_pipeline.add_component("embedder", document_embedder)
indexing_pipeline.add_component("document_writer", document_writer)

indexing_pipeline.connect("pdf_converter", "document_cleaner")
indexing_pipeline.connect("document_cleaner", "document_splitter")
indexing_pipeline.connect("document_splitter", "embedder")
indexing_pipeline.connect("embedder", "document_writer")

document_path = ["ADD_PDF_HERE.pdf"]
indexing_pipeline.run({"pdf_converter": {"sources": document_path}})
```

**Describe your environment (please complete the following information):**
 - Pythen 3.11
 - Haystack version: 2.7.0
 - Integration (Langfuse) version: 0.5.0

**Comment by silvanocerza** [comment]
Caused by deepset-ai/haystack#8489 for sure. Will investigate.

**Comment by alex-stoica** [comment]
It's because the `trace` from `Tracer` expects `parent_span` 
```python
class Tracer(abc.ABC):
    """Interface for instrumenting code by creating and submitting spans."""

    @abc.abstractmethod
    @contextlib.contextmanager
    def trace(
        self, operation_name: str, tags: Optional[Dict[str, Any]] = None, parent_span: Optional[Span] = None
    ) -> Iterator[Span]:
 ```
 while `trace` from `LangfuseTracer(Tracer)` does not 
https://github.com/deepset-ai/haystack-core-integrations/blob/61ac2f457c53697e8f906d9f44c39995a008f140/integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py#L120

**Comment by alex-stoica** [comment]
This is not the only bug, the line
 https://github.com/deepset-ai/haystack-core-integrations/blob/61ac2f457c53697e8f906d9f44c39995a008f140/integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py#L141
 
  became useless, returns 
 
``` {'haystack.component.name': 'llm_english', 'haystack.component.type': 'AzureOpenAIGenerator', 'haystack.component.input_types': {'system_prompt': 'NoneType', 'streaming_callback': 'NoneType', 'generation_kwargs': 'NoneType', 'prompt': 'str'}, 'haystack.component.input_spec': {'prompt': {'type': 'str', 'senders': ['prompt_builder_translate']}, 'system_prompt': {'type': 'typing.Optional[str]', 'senders': []}, 'streaming_callback': {'type': 'typing.Optional[typing.Callable[[haystack.dataclasses.streaming_chunk.StreamingChunk], NoneType]]', 'senders': []}, 'generation_kwargs': {'type': 'typing.Optional[typing.Dict[str, typing.Any]]', 'senders': []}}, 'haystack.component.output_spec': {'replies': {'type': 'typing.List[str]', 'receivers': []}, 'meta': {'type': 'typing.List[typing.Dict[str, typing.Any]]', 'receivers': []}}, 'haystack.component.visits': 1}```

i.e. no "meta" retrievable
