### ISSUE TITLE
Qdrant integration

### ISSUE THREAD

**Issue by silvanocerza** [deepset-ai/haystack-core-integrations#121]
## Summary and motivation

The integration has already been made and published.

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.

- [x] The code was merged in the `main` branch
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] There is an example available to demonstrate the feature
- [x] The feature was announced through social media

**Comment by silvanocerza** [comment]
On hold cause we're waiting for integrations documentation to be easily integrated with the rest of the Haystack core documentation.

**Comment by dfokina** [comment]
Both Retriever and Document Store docs for Qdrant are published :)

**Comment by silvanocerza** [comment]
Closing, checklist is completed. 💯
