### ISSUE TITLE
Google Gemini (Rest API) Integration

### ISSUE THREAD

**Issue by TuanaCelik** [deepset-ai/haystack-core-integrations#135]
## Summary and motivation

Google Gemini isn't only provided via Vertex AI. Let's create an integration for the REST API offering, too. There you only need a simple API Key  - no need for a GCP account.

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.

- [x] The code was merged in the `main` branch
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] There is an example available to demonstrate the feature
- [x] The feature was announced through social media

**Comment by silvanocerza** [comment]
To support Gemini through [Makersuite](https://makersuite.google.com/) we will probably need to use a different library from the one used in Vertex AI.

We'll need `google-generativeai`, at least version `0.3.1`. This because the `google-cloud-aiplatform` library used in the Google Vertex AI integration doesn't support Makersuite. Documentation is over [here](https://ai.google.dev/docs). Library repo [here](https://github.com/google/generative-ai-python). [Here](https://makersuite.google.com/app/apikey) to get the API key instead.


Also note that Makersuite is only available in the USA, a VPN should do the trick.

**Comment by TuanaCelik** [comment]
Would the ideal name for this integration be `gemini-haystack` or `makersuite-haystack` or something else? Wdyt?

**Comment by TuanaCelik** [comment]
Expanding on the comment above: especially if we want to document all of these integrations (which we do), we might end up wanting to rethink how we name them. E.g., in the google-vertexai-haystack integration we have the `GeminiGeneroator`, if this is to be a separate integration here, we probably want to start naming them to be explicit in _how_ they're using Gemini??

E.g.: `VertexAIGeminiGenerator` and `MakersuiteGeminiGenerator` - I may be well off here.. Lmk what you think

**Comment by TuanaCelik** [comment]
Here's the draft PR when someone from core is back to finalize it: https://github.com/deepset-ai/haystack-core-integrations/pull/156

It has an example notebook in there. Works with:
- gemini-pro for just tex
- gemini-pro-vision for text + image
- GeminiChatGenerator for function calling

Needs:
- probably lots of name/package name changes to distinguish from the vertex counterpart
- tests :) 
Leaving it in draft in case you'd rather bin it

**Comment by TuanaCelik** [comment]
@dfokina @silvanocerza Let's get the docs going. Feel free to assign to me if needed. I can also take the example/demonstration.
@bilgeyucel or @annthurium do one of you have room for the integration page? Or to switch the demo with me?

**Comment by dfokina** [comment]
@TuanaCelik @silvanocerza Docs are live: https://docs.haystack.deepset.ai/v2.0/docs/googleaigeminichatgenerator & https://docs.haystack.deepset.ai/v2.0/docs/googleaigeminigenerator
