### ISSUE TITLE
create API reference for core-integrations

### ISSUE THREAD

**Issue by dfokina** [deepset-ai/haystack-core-integrations#136]
We need to create an API reference for haystack-core-integrations that would be loaded to our Haystack docs to Readme editor: https://docs.haystack.deepset.ai/v2.0/reference

```[tasklist]
### Tasks
- [ ] Generate the api docs in markdown format for all the integrations https://github.com/deepset-ai/haystack-core-integrations/issues/274
- [ ] Sync the api docs with readme.com https://github.com/deepset-ai/haystack-core-integrations/pull/266
```

**Comment by silvanocerza** [comment]
We also need to setup a workflow similar to [this one](.github/workflows/readme_sync.yml) so that they are uploaded to our documentation page.

**Comment by masci** [comment]
superseded by https://github.com/deepset-ai/haystack-core-integrations/issues/274
