### ISSUE TITLE
Add AzureOpenAIEmbedders

### ISSUE THREAD

**Issue by mathislucka** [deepset-ai/haystack-core-integrations#138]
**Is your feature request related to a problem? Please describe.**
OpenAI's embedding models hosted on Azure are widely used. We should add the relevant embedders to support them.

See also: https://github.com/deepset-ai/haystack/issues/6620

**Describe the solution you'd like**
Similar to 1.x support the OpenAI embedding models hosted on Azure.

**Describe alternatives you've considered**
None

**Comment by masci** [comment]
Fixed in https://github.com/deepset-ai/haystack/pull/6676
