### ISSUE TITLE
Add AzureOpenAIGenerator

### ISSUE THREAD

**Issue by mathislucka** [deepset-ai/haystack-core-integrations#141]
**Is your feature request related to a problem? Please describe.**
We should support Azure Open AI services. It's a widely used service that is particularly relevant for professional production use.

See also: https://github.com/deepset-ai/haystack/issues/6620

**Describe the solution you'd like**
Similar to 1.x we need a component that supports OpenAI models hosted on Azure.

**Describe alternatives you've considered**
None

**Comment by masci** [comment]
@vblagoje Can we close this now that we merged https://github.com/deepset-ai/haystack/pull/6648 ?

**Comment by vblagoje** [comment]
Yes, completed with https://github.com/deepset-ai/haystack/pull/6648 Closing

**Comment by vblagoje** [comment]
@masci @mathislucka we decided to keep Azure Generators inside the haystack project codebase as it doesn't introduce any new dependencies.
