### ISSUE TITLE
Add PGVector DocumentStore

### ISSUE THREAD

**Issue by mathislucka** [deepset-ai/haystack-core-integrations#142]
## Summary and motivation
PGVector is a popular request from our community. We should have it in 2.0.

## Detailed design

TBD

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.

- [x] The code was merged in the `main` branch
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations (https://github.com/deepset-ai/haystack-integrations/pull/162)
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] There is an example available to demonstrate the feature
- [x] The feature was announced through social media

**Comment by sahusiddharth** [comment]
@mathislucka I have started working on this, can you clarify something for me?

When it comes to metadata filtering there is way suggested in the [template](https://github.com/deepset-ai/document-store), but the one followed in [chroma docstore](https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/chroma/src/chroma_haystack/document_store.py#L55) is quite different, how should I proceed from here?

**Comment by anakin87** [comment]
Hey @sahusiddharth, sorry for the late reply.

I recently developed the [Pinecone Document Store](https://github.com/deepset-ai/haystack-core-integrations/tree/main/integrations/pinecone), so I try to share some suggestions.

- the official metadata filtering is that of the template. You can find more information [in the docs](https://docs.haystack.deepset.ai/v2.0/docs/metadata-filtering).
I think filters in Chroma Document Store are the legacy filters.

- as explained in [Creating Custom Document Stores](https://docs.haystack.deepset.ai/v2.0/docs/creating-custom-document-stores), each Document Store must respect the Document Store protocol, by implementing the 4 standard methods (respecting their signature). For functions that are specific to your Document Store, you are free to implement any other methods you need.

- **incremental development**: I suggest you create one of the 4 standard methods at a time and test it. [`DocumentStoreBaseTests`](https://github.com/deepset-ai/haystack/blob/d61ac9e6ae4463edbb24c0ed69858cf2dc2b31ea/haystack/testing/document_store.py#L1251) was recently refactored to allow this.
An example
  1. you implement `count_documents`
  2. in test_document_store.py, you define the test class `TestDocumentStore(CountDocumentsTest)`: please note that here we are only inheriting from `CountDocumentsTest`
  3. you make tests pass
  4. you implement `write_documents`
  5. in test_document_store.py, you define the testing class `TestDocumentStore(CountDocumentsTest, WriteDocumentsTest)`: here we are also inheriting from `WriteDocumentsTest`
  6. ...

- [Elasticsearch Document Store](https://github.com/deepset-ai/haystack-core-integrations/tree/main/integrations/elasticsearch) can be considered a good reference, also for the implementation of filters

Feel free to ask for clarification, if needed!
