### ISSUE TITLE
Add MongoDBAtlasDocumentStore

### ISSUE THREAD

**Issue by mathislucka** [deepset-ai/haystack-core-integrations#143]
## Summary and motivation
Similar to 1.x we'd like to have a document store for MongoDB's Atlas.

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.

- The code was merged in the `main` branch: 
  - [x] Docstore itself: https://github.com/deepset-ai/haystack-core-integrations/pull/413
  - [x] First retriever: https://github.com/deepset-ai/haystack-core-integrations/pull/427
  - [x] Filtering:
- [x] Docs are published at https://docs.haystack.deepset.ai/: Draft at https://www.notion.so/deepsetai/MongoDBAtlasDocumentStore-WIP-e2b17f3079804ac6a69384789f83b2ce
- [x] There is a Github workflow running the tests for the integration nightly and at every PR: https://github.com/deepset-ai/haystack-core-integrations/pull/413
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated: https://github.com/deepset-ai/haystack-core-integrations/pull/413
- [x] The package has been released on PyPI 
- [x] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations: https://github.com/deepset-ai/haystack-integrations/pull/180 
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README: https://github.com/deepset-ai/haystack-core-integrations/pull/413
- [x] There is an example available to demonstrate the feature: https://github.com/deepset-ai/haystack-core-integrations/pull/413
- [x] The feature was announced through social media

**Comment by anakin87** [comment]
Filters implemented and new version released.
