### ISSUE TITLE
Add Ollama Generator

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#146]
## Summary and motivation

See https://github.com/deepset-ai/haystack/issues/6514

## Detailed design

See https://github.com/deepset-ai/haystack/issues/6514

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.

- [x] The code was merged in the `main` branch
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] There is an example available to demonstrate the feature
- [x] The feature was announced through social media

**Comment by anakin87** [comment]
@AlistairLR112 we can continue working on this integration, using the checklist above.
I can work on drafting docs, in collaboration with the documentation team.

You can choose what you want:
- create a PR in https://github.com/deepset-ai/haystack-integrations to showcase this integration
- create an example: can be a python script ([Chroma example](https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/chroma/example/example.py)) or a notebook ([Pinecone example](https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/pinecone/examples/pinecone_documentstore_example.ipynb))

Of course, if you don't have time, I'll take care of it...

FYI @bilgeyucel @dfokina

**Comment by AlistairLR112** [comment]
Am happy to take it on :)

**Comment by AlistairLR112** [comment]
Example started here: https://github.com/deepset-ai/haystack-core-integrations/pull/170

**Comment by AlistairLR112** [comment]
Tile added: https://github.com/deepset-ai/haystack-integrations/pull/108

**Comment by dfokina** [comment]
Docs are published: https://docs.haystack.deepset.ai/v2.0/docs/ollamagenerator

**Comment by AlistairLR112** [comment]
Hello everyone, one thing I have noticed we need to add in the docs and the example is the mapping of the volumes in docker - this has already been done in the CI pipeline

We need to add `-v ollama:/root/.ollama ` to the docker run command

**Comment by anakin87** [comment]
@AlistairLR112 please correct me if I am wrong.
This is only needed to create a persistent volume for Ollama.

**Comment by AlistairLR112** [comment]
Ah whoops, you are right, was thinking it was mapping the entrypoint! 

False alarm!!!

**Comment by anakin87** [comment]
Opened a PR in Ollama to mention the integration in their README: https://github.com/jmorganca/ollama/pull/1808

**Comment by masci** [comment]
Why `Haystack LLM framework` and not just `Haystack`? https://github.com/jmorganca/ollama/pull/1808/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R302

Can you fix that?
