### ISSUE TITLE
AstraDB document store

### ISSUE THREAD

**Issue by masci** [deepset-ai/haystack-core-integrations#147]
## Summary and motivation

DataStax Astra DB is a serverless vector database that’s perfect for managing mission-critical AI workloads. It’s built on Apache Cassandra®, making Astra DB a highly scalable, reliable database technology. This makes it a powerful all-in-one data storage solution, ideal for Generative AI projects.

## Detailed design

Implement the `DocumentStore` protocol and provide a specific documents retriever.

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.

- [x] The code was merged in the `main` branch https://github.com/deepset-ai/haystack-core-integrations/pull/144
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] #164
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] #163
- [x] The feature was announced through social media

**Comment by julian-risch** [comment]
Done! 🎉
