### ISSUE TITLE
Docs: UnstructuredFileConverter

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-core-integrations#148]
**Is your feature request related to a problem? Please describe.**
Documentation for UnstructuredFileConverter is missing. Here's the integration page for it: https://haystack.deepset.ai/integrations/unstructured-file-converter

**Describe the solution you'd like**
Adding a new documentation page for this converter. We' can then use this page in its integration page as well.

**Comment by bilgeyucel** [comment]
@davidsbatista There should be a new documentation page under https://docs.haystack.deepset.ai/v2.0/docs/converters as this is an integration that the deepset team maintains

**Comment by dfokina** [comment]
@bilgeyucel @davidsbatista the docs are published https://docs.haystack.deepset.ai/v2.0/docs/unstructuredfileconverter
