### ISSUE TITLE
Docs: Vertex AI integration docs

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-core-integrations#155]
```[tasklist]
### Tasks
- [x] VertexAITextGenerator
- [x] VertexAICodeGenerator
- [x] VertexAIImageGenerator
- [x] VertexAIImageQA
```
When they're published, we should link them from the "Google Vertex AI integration" page

**Comment by dfokina** [comment]
All documentation pages are published @bilgeyucel @silvanocerza 
https://docs.haystack.deepset.ai/v2.0/docs/vertexaicodegenerator
https://docs.haystack.deepset.ai/v2.0/docs/vertexaiimagegenerator
https://docs.haystack.deepset.ai/v2.0/docs/vertexaiimageqa
https://docs.haystack.deepset.ai/v2.0/docs/vertexaitextgenerator
