### ISSUE TITLE
Ollama: investigate/implement ChatGenerator

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#168]
It should be possible to pass ChatMessages to LLMs served via Ollama, as done in [`OpenAIChatGenerator`](https://github.com/deepset-ai/haystack/blob/main/haystack/components/generators/chat/openai.py).

We should investigate whether this is feasible and if so create a ChatGenerator.

**Comment by AlistairLR112** [comment]
https://github.com/deepset-ai/haystack-core-integrations/pull/176 - Initial attempt here

**Comment by AlistairLR112** [comment]
Will need to create an integration tile but will be away for the next 2 days

**Comment by anakin87** [comment]
done in #176
