### ISSUE TITLE
Llama.cpp Generator

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#177]
## Summary and motivation

[Llama.cpp](https://github.com/ggerganov/llama.cpp) is an important project in this field and having an integration with it would be great.
@awinml worked on something related.

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.

- [x] The code was merged in the `main` branch
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations https://github.com/deepset-ai/haystack-integrations/pull/118
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] There is an example available to demonstrate the feature
- [x] #259

**Comment by anakin87** [comment]
@awinml can you also open a PR in https://github.com/deepset-ai/haystack-integrations? 🙏

**Comment by awinml** [comment]
@anakin87 Yes, I will do that!
