### ISSUE TITLE
Add workflow to publish docstring

### ISSUE THREAD

**Issue by silvanocerza** [deepset-ai/haystack-core-integrations#185]
As of now docstrings for all integrations are not published anywhere. 

We need to setup a workflow similar to [this one](.github/workflows/readme_sync.yml) so that they are uploaded to our documentation page.

**Comment by anakin87** [comment]
Maybe related: #136

**Comment by silvanocerza** [comment]
Indeed it is, I'm closing this one and adding more context on the other.
