### ISSUE TITLE
Ollama: support Embedders

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#190]
Currently, the Ollama integration only supports Generators (LLMs) and not Embedders.

However, the Ollama project has [some support for embedders](https://github.com/jmorganca/ollama/blob/main/docs/api.md#generate-embeddings).
It should be noted that most of the [currently available models](https://ollama.ai/library) are not great for producing embeddings.

**Comment by AlistairLR112** [comment]
I can have a look on the weekend :)

**Comment by AlistairLR112** [comment]
https://github.com/deepset-ai/haystack-core-integrations/pull/194

**Comment by jmdevita** [comment]
Hello! I was working on Haystack with my Ollama model and realized there wasn't a DocumentEmbedder. I stumbled across this thread and built my own by using the pre-existing document models from haystack and the currently built TextEmbedder to keep parity. I can submit my branch with the Ollama Document Embedder included & tests if it helps.

**Comment by jmdevita** [comment]
#400

**Comment by lekhnath** [comment]
I am also interested in using local gguf model for document embedder. Any suggestions to do it manually for now?

Thanks.

**Comment by anakin87** [comment]
@lekhnath Ollama Document Embedder has been merged some time ago. You can find the docs here: https://docs.haystack.deepset.ai/docs/ollamadocumentembedder
