### ISSUE TITLE
google_vertex: mount integration under haystack_integrations.*

### ISSUE THREAD

**Issue by masci** [deepset-ai/haystack-core-integrations#200]
## Checklist

- [x] Update the structure, the code, and examples on haystack-core-integrations
- [x] Update the integration tile on https://github.com/deepset-ai/haystack-integrations https://github.com/deepset-ai/haystack-integrations/pull/151
- [x] Update the docs at https://docs.haystack.deepset.ai/
- [x] Update the notebooks on https://github.com/deepset-ai/haystack-cookbook (if needed) https://github.com/deepset-ai/haystack-cookbook/pull/29

**Comment by TuanaCelik** [comment]
Another todo to add is the blog, I'm updating it now, but jfyi for the next ones, some may have articles attached: https://haystack.deepset.ai/blog/gemini-models-with-google-vertex-for-haystack
