### ISSUE TITLE
ollama: mount integration under haystack_integrations.*

### ISSUE THREAD

**Issue by masci** [deepset-ai/haystack-core-integrations#209]

**Comment by anakin87** [comment]
## Checklist

- [ ] Update the structure, the code, and examples on haystack-core-integrations
- [ ] Update the integration tile on https://github.com/deepset-ai/haystack-integrations
- [ ] Update the docs at https://docs.haystack.deepset.ai/
- [ ] Update the notebooks on https://github.com/deepset-ai/haystack-cookbook (if needed)
