### ISSUE TITLE
`Pinecone-python-client` v3.0.0 breaks `pinecone-haystack`

### ISSUE THREAD

**Issue by awinml** [deepset-ai/haystack-core-integrations#223]
**Describe the bug**

The version 3.0.0 of [`pinecone-python-client`](https://github.com/pinecone-io/pinecone-python-client) is a big update and introduces a lot of changes. This new version is not compatible with the current implementation of `pinecone-haystack` and the code breaks as soon as you try to initialize the document store.

**To Reproduce**

The global `pinecone.init` has been removed, so `pinecone-haystack` gives an error as soon as you try to initialize the document store with the new version of `pinecone-python-client`.

Please see this [Colab notebook](https://colab.research.google.com/drive/1txmh436Q8ki8twbzAqbLq8C3wmJ4rv9l?usp=sharing) for more information.

**Immediate Fix**

Pin `pinecone-client` to version 2.2.4 in the [`pinecone-haystack` dependencies](https://github.com/deepset-ai/haystack-core-integrations/blob/ed043a0ff8783f333e3c3990e3b0badaa574237f/integrations/pinecone/pyproject.toml#L28C21-L28C21).

**Describe the solution you'd like**

Refactor `pinecone-haystack` to support the new version. 

The new version introduces a lot of new features. Some of the changes include:
- Serverless indexes
- Global state variables set with pinecone.init have been refactored into new Pinecone class instances that encapsulate their configuration state.
- Everything GRPC-related is now moved into a subpackage, `pinecone.grpc`, so that GRPC code is only imported when needed.
- The `list_indexes` and `list_collections` methods now return an array with full descriptions of each resource, not merely an array of names.
- The Pinecone SDK now has a Apache 2.0 license.

Please see the [Migration Guide for version 3.0.0](https://canyon-quilt-082.notion.site/Pinecone-Python-SDK-v3-0-0-Migration-Guide-056d3897d7634bf7be399676a4757c7b#406cf21819f64cafaf8fa677b44ef44f) for more information.

**Describe your environment:**

 - OS: Linux
 - Haystack version: haystack-ai - 2.0.0-beta.4
 - Integration version: pinecone-haystack - 0.0.1

**Comment by anakin87** [comment]
Thank you for reporting this!

I would adopt the immediate fix and then refactor the Document Store.

**Comment by masci** [comment]
0.1.0 was released to ship the temporary workaround

**Comment by bilgeyucel** [comment]
We can resolve #715 with this upgrade

**Comment by mmurraysans** [comment]
Hi All,

I took a pass at updating this to the new client in #756

**Comment by anakin87** [comment]
```[tasklist]
- [ ] Upgrade the Document Store and Retriever (#793)
- [ ] Update examples
- [ ] The package has been released on PyPI
- [ ] Docs at https://docs.haystack.deepset.ai/ were updated
- [ ] Integration tile on https://github.com/deepset-ai/haystack-integrations was updated
```
