### ISSUE TITLE
astra extension import errors with Haystack v2.0.0-beta.5

### ISSUE THREAD

**Issue by annthurium** [deepset-ai/haystack-core-integrations#231]
**Describe the bug**
When trying to import the AstraDocumentStore, I get an error: 
```python
from astra_haystack.document_store import AstraDocumentStore
```
```python
[/usr/local/lib/python3.10/dist-packages/astra_haystack/document_store.py](https://localhost:8080/#) in <module>
     10 from haystack import default_from_dict, default_to_dict
     11 from haystack.dataclasses import Document
---> 12 from haystack.document_stores import (
     13     DuplicateDocumentError,
     14     DuplicatePolicy,

ImportError: cannot import name 'DuplicateDocumentError' from 'haystack.document_stores' (/usr/local/lib/python3.10/dist-packages/haystack/document_stores/__init__.py)
```
I think this is because in the beta.5 release, the folder configuration has changed and now errors and DuplicatePolicy are now under the `errors` and `types` sub-folders.

**To Reproduce**
Steps to reproduce the behavior. Feel free to link a Colab we can run to investigate the issue.
https://colab.research.google.com/drive/1WiRWYji4hbGGzuXZ_uTRagssOp4LbLga#scrollTo=A1iA_0dmXV3L
This colab requires a bunch of env variables to connect to Astra but since this error happens before the DB connection I think you can just put in dummy strings for those

**Describe your environment (please complete the following information):**
 - OS: MacOS Ventura 13.6.2
 - Haystack version: 2.0.0-beta5
 - Integration version: 0.1.0

**Comment by anakin87** [comment]
Fixed in #235
