### ISSUE TITLE
Add DeepEval evaluation framework integration

### ISSUE THREAD

**Issue by julian-risch** [deepset-ai/haystack-core-integrations#250]
## Summary and motivation

Integrate the DeepEval evaluation framework by implementing a new DeepEvalEvaluator component

## Detailed design

Based on the proposal https://github.com/deepset-ai/haystack/pull/6784 we need to implement an DeepEvalEvaluator component that is initialized with one metric and an OpenAI API key. Depending on the particular metric, the component expects for example question, answer and context as input and outputs a dictionary with the calculated score.

## Checklist

If the request is accepted, ensure the following checklist is complete before closing this issue.

- [x] The code is documented with docstrings and was merged in the `main` branch
- [x] Docs are published at https://docs.haystack.deepset.ai/
- [x] There is a Github workflow running the tests for the integration nightly and at every PR
- [x] A label named like `integration:<your integration name>` has been added to this repo
- [x] The [labeler.yml](https://github.com/deepset-ai/haystack-core-integrations/blob/main/.github/labeler.yml) file has been updated
- [x] The package has been released on PyPI
- [x] An integration tile has been added to https://github.com/deepset-ai/haystack-integrations
- [x] The integration has been listed in the [Inventory section](https://github.com/deepset-ai/haystack-core-integrations#inventory) of this repo README
- [x] There is an example available to demonstrate the feature
- [x] The feature was announced through social media

**Comment by sahusiddharth** [comment]
@julian-risch can I work on this?

**Comment by julian-risch** [comment]
With the social media announcement, this issue is closed now: https://twitter.com/Haystack_AI/status/1760726816526925839
