### ISSUE TITLE
Run integration tests for Amazon Sagemaker in CI

### ISSUE THREAD

**Issue by ZanSara** [deepset-ai/haystack-core-integrations#287]
**Is your feature request related to a problem? Please describe.**
Right now the integration tests don't run in CI. This makes the integration tested only by unit tests.

**Describe the solution you'd like**
If Sagemaker endpoints can be deployed on demand, running these tests nightly or weekly should be possible. In that case we should run them in CI.

**Describe alternatives you've considered**
Not running them.

**Comment by shadeMe** [comment]
Running the integration tests on the CI would require deploying models on Sagemaker, which is not cost-effective. The unit tests will have to do for now.
