### ISSUE TITLE
Update core integration secret managment - Amazon Bedrock

### ISSUE THREAD

**Issue by shadeMe** [deepset-ai/haystack-core-integrations#364]
- [x] Code https://github.com/deepset-ai/haystack-core-integrations/pull/416
- [x] Documentation
- [x] Tutorials
- [x] Cookbooks
- [x] Articles
- [x] Integration Tiles

**Comment by davidsbatista** [comment]
ups, somehow missed that, I will update them.

**Comment by davidsbatista** [comment]
updated
