### ISSUE TITLE
Update core integration secret managment - Qdrant

### ISSUE THREAD

**Issue by shadeMe** [deepset-ai/haystack-core-integrations#372]
- [x] Code (c.f https://github.com/deepset-ai/haystack-core-integrations/pull/347)
- [x] Documentation
- [x] Tutorials
- [x] Cookbooks
- [x] Articles
- [x] Integration Tiles

**Comment by bilgeyucel** [comment]
We dont have any articles around Qdrant. This issue is resolved

**Comment by lambda-science** [comment]
Hello @bilgeyucel @shadeMe the Secret update has been merged but the new version of the package doesn't contain it. v3.0.0, is it possible to publish a new version with the new secret handling ?

**Comment by anakin87** [comment]
@lambda-science done right now: https://pypi.org/project/qdrant-haystack/3.1.0/
