### ISSUE TITLE
Push the OptimumEmbedders to their performance limits

### ISSUE THREAD

**Issue by mathislucka** [deepset-ai/haystack-core-integrations#384]
**Background**
The OptimumEmbedders optimize inference speed for embedding inference. We have a basic version almost ready. In this task, we want to push these embedding components to their performance limits.

**Ideas**
- optimize data loading
- optimize batching
- optimize TensorRT engine build
- try FP16 inference
- play with further optimizations (ORTOptimizer, ORTQuantizer)

**Comment by shadeMe** [comment]
Blocked on https://github.com/deepset-ai/haystack-core-integrations/issues/137
