### ISSUE TITLE
Update Sagemaker workflow to run integration tests

### ISSUE THREAD

**Issue by silvanocerza** [deepset-ai/haystack-core-integrations#431]
Sagemaker integration tests are not being run as of now.

Keeping models deployed just for testing purposes is way too expensive. We should start them on demand when the workflow needs to run and undeploy them when it finishes.

This will give us the chance to verify the correct functionality of our integration and keep cost down.

**Comment by shadeMe** [comment]
C.f - https://github.com/deepset-ai/haystack-core-integrations/issues/287
