### ISSUE TITLE
Uptrain integration tests failing

### ISSUE THREAD

**Issue by masci** [deepset-ai/haystack-core-integrations#464]
**Describe the bug**
I have `OPENAI_API_KEY` set.

`hatch run test` fails 4 tests with:

```
FAILED tests/test_evaluator.py::test_integration_run[critique_language-inputs7-None] - ValueError: UpTrain evaluator did not return an expected output for metric 'fluency'
FAILED tests/test_evaluator.py::test_integration_run[critique_tone-inputs8-metric_params8] - ValueError: UpTrain evaluator did not return an expected output for metric 'tone'
FAILED tests/test_evaluator.py::test_integration_run[guideline_adherence-inputs9-metric_params9] - polars.exceptions.SchemaFieldNotFoundError: score_somename_adherence
FAILED tests/test_evaluator.py::test_integration_run[response_matching-inputs10-metric_params10] - ValueError: Row 0 is missing required all required attributes for evaluation: {'ground_truth', 'question', 'response'}
``` 

**Describe your environment (please complete the following information):**
 - Haystack version:
 - Integration version:

**Comment by julian-risch** [comment]
We released version 0.4.1 of our [uptrain-haystack](https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/uptrain) integration now, where we pin the uptrain version to 0.5.0. The issue does not occur with that older version of uptrain and integration tests are very slow but run through.
