### ISSUE TITLE
Support Pinecone's hybrid vectors

### ISSUE THREAD

**Issue by yasyf** [deepset-ai/haystack-core-integrations#483]
**Is your feature request related to a problem? Please describe.**
Recently, Pinecone announced support for [Sparse-dense embeddings](https://docs.pinecone.io/docs/hybrid-search), allowing for hybrid vector search (both semantic and keyword search). However, `haystack` doesn't currently support these.

**Describe the solution you'd like**
Native support for sparse-dense vectors!

**Describe alternatives you've considered**
I've created a small package called [`haystack-hybrid-embedding`](https://github.com/yasyf/haystack-hybrid-embedding) which can be installed to support hybrid vectors for now, but it's a hack!

**Comment by anakin87** [comment]
closing in favor of #695
