### ISSUE TITLE
Release new `llama-cpp-haystack` version

### ISSUE THREAD

**Issue by awinml** [deepset-ai/haystack-core-integrations#492]
**Describe the bug**
The `model_path` parameter was renamed to `model` in #243. This change is not reflected on the current `llama-cpp-haystack` version on pypi.
The documentation showcases the new API with `model`, causing a mismatch.

**To Reproduce**
To download the model:
```bash
curl -L -O "https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF/resolve/main/openhermes-2.5-mistral-7b.Q4_K_M.gguf"
```

```python
from haystack_integrations.components.generators.llama_cpp import LlamaCppGenerator

generator = LlamaCppGenerator(
    model="openhermes-2.5-mistral-7b.Q4_K_M.gguf", 
    n_ctx=512,
    n_batch=128,
    generation_kwargs={"max_tokens": 128, "temperature": 0.1},
)
generator.warm_up()
prompt = f"Who is the best American actor?"
result = generator.run(prompt)
```

**Describe your environment (please complete the following information):**
 - OS: `Linux`
 - Haystack version: `haystack-ai==2.0.0b8`
 - Integration version: `llama-cpp-haystack==0.2.1`

**Comment by anakin87** [comment]
Thanks for reporting this!

I've just released a new version: https://pypi.org/project/llama-cpp-haystack/0.3.0/
