### ISSUE TITLE
Cannot import /  find module named 'haystack_integrations.components.embedders'

### ISSUE THREAD

**Issue by Croccodoyle** [deepset-ai/haystack-core-integrations#563]
I am trying to run the sample code here:
https://haystack.deepset.ai/integrations/mongodb#overview but cannot import haystack_integrations.components.embedders

**To Reproduce**
Running locally on python 3.11

**Describe your environment (please complete the following information):**
 - Sonoma 14.3.1 with Python 3.11
 - Haystack version: 2.0
 - Integration version:  2.0

**Comment by Croccodoyle** [comment]
Resolved

Code on https://haystack.deepset.ai/integrations/mongodb#overview   is:

from haystack_integrations.components.embedders.mongodb_atlas import MongoDBAtlasEmbeddingRetriever

Code should read:

from haystack_integrations.components.retrievers.mongodb_atlas import MongoDBAtlasEmbeddingRetriever

**Comment by masci** [comment]
Thank you! Opened a PR to fix it here https://github.com/deepset-ai/haystack-integrations/pull/205
