### ISSUE TITLE
UpTrain integration breaks due to upstream changes

### ISSUE THREAD

**Issue by shadeMe** [deepset-ai/haystack-core-integrations#571]
**Describe the bug**
See https://github.com/deepset-ai/haystack-core-integrations/pull/564.

**Comment by lbux** [comment]
I actually think this ends up being a "bug" with UpTrain where their docs/code didn't match up for this release.

I went through their 0.5.0 release and we can see [their docs](https://github.com/uptrain-ai/uptrain/blob/7c1618febf381adb5b2a5c76d2bfca40320bba1e/docs/key-components/evals.mdx) lists `ResponseMatching` as needing `question` and `ground_truth` while their [code expects](https://github.com/uptrain-ai/uptrain/blob/7c1618febf381adb5b2a5c76d2bfca40320bba1e/uptrain/framework/evalllm.py) `response` and `ground_truth`.

**Comment by masci** [comment]
Closing as the integration was transferred to https://github.com/uptrain-ai/uptrain
