### ISSUE TITLE
Integration tests are skipped

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#595]
Currently, some of the tests for these integrations are skipped because the expected env var is not set:
- ~ragas~ 
- ~uptrain~
- ~deepeval~ 
- [x] nvidia
- [x] gradient https://github.com/deepset-ai/haystack-core-integrations/pull/625
- [x] astra https://github.com/deepset-ai/haystack-core-integrations/pull/623

It happens for different reasons. We should understand why and fix this issue.

**Comment by silvanocerza** [comment]
API key for Nvidia integration added, integration tests should run now.

**Comment by anakin87** [comment]
@silvanocerza yes!
Those with nvcf backend run fine: https://github.com/deepset-ai/haystack-core-integrations/actions/runs/8444638551/job/23146314844
