### ISSUE TITLE
compoment like langchain sql agent 

### ISSUE THREAD

**Issue by DavidSche** [deepset-ai/haystack-core-integrations#611]
**Is your feature request related to a problem? Please describe.**

Provide a component that can extract and generate sql from dialogue questions and answers like langchain sql agent, obtain data in relational databases, and use LLM to perform statistical analysis on the data

**Describe the solution you'd like**

You can access the data table through the database connection configured by the component, generate the corresponding SQL statement through the description information of the database table and fields, query the data, and then use LLM to perform statistical analysis on the data.

**Describe alternatives you've considered**

**Additional context**

**Comment by masci** [comment]
Hi @DavidSche do you have any pointer to help us understanding how this component should look like? A fully-working langchain app would be best but link to docs or blog posts would be super helpful
