### ISSUE TITLE
Add streaming support in `OllamaChatGenerator`

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-core-integrations#614]
**Is your feature request related to a problem? Please describe.**
`OllamaChatGenerator` doesn't support streaming

**Describe the solution you'd like**
There's already support for OllamaGenerator and we should implement the streaming support for `OllamaChatGenerator`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by julian-risch** [comment]
Closed by https://github.com/deepset-ai/haystack-core-integrations/pull/757
