### ISSUE TITLE
Add an ability to select an index after initializing the document_store in Elasticsearch 8

### ISSUE THREAD

**Issue by PAHXO** [deepset-ai/haystack-core-integrations#617]
We used to select indices at runtime i.e. when using the retriever or writing documents into the document_store.
I used to be able to that easily. in haystack 1.x. Now I cannot I.

I have lots of indices, and I'd like to change them quite often.

My current workaround is to combine the retriever and the document_store into a function so I can one line them in my code.

I mainly use Elasticsearch 8.

**Comment by anakin87** [comment]
Hello!

Are there problems with creating new Document Store instances when changing indexes?

In Haystack 2.x, in general, a Document Store maps to an index (or a similar abstraction in other DBs).
