### ISSUE TITLE
Docs: `CohereRanker`

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#648]
@AnushreeBannadabhavi will kindly create a draft.

**Comment by anakin87** [comment]
@AnushreeBannadabhavi in case you want to help with this, check your Discord account for a message from me.
(I can share a draft with you).

**Comment by AnushreeBannadabhavi** [comment]
Hi @anakin87!
I updated the draft. Let me know if any more changes are needed.

**Comment by anakin87** [comment]
@dfokina FYI.

**Comment by dfokina** [comment]
Hello @AnushreeBannadabhavi , @anakin87  - the docs are live: https://docs.haystack.deepset.ai/docs/cohereranker
