### ISSUE TITLE
Add support for custom mapping when creating a new index using `ElasticsearchDocumentStore`

### ISSUE THREAD

**Issue by silvanocerza** [deepset-ai/haystack-core-integrations#655]
**Is your feature request related to a problem? Please describe.**
This is not related a problem, it's an additional functionality.

**Describe the solution you'd like**

I'd like to use a custom mapping when using `ElasticsearchDocumentStore` and creating a new index.

**Describe alternatives you've considered**

N/A

**Additional context**

This stems from [this discussion](https://github.com/deepset-ai/haystack/discussions/7451).

As of now mappings are hardcoded [here](https://github.com/deepset-ai/haystack-core-integrations/blob/363c7b5a96867c7b4eec2d256b600878f81f1daa/integrations/elasticsearch/src/haystack_integrations/document_stores/elasticsearch/document_store.py#L107-L127).

**Comment by AnushreeBannadabhavi** [comment]
I'd like to take it up if no one is working on it!

**Comment by silvanocerza** [comment]
Cool! @AnushreeBannadabhavi feel free to open a PR. :)
