### ISSUE TITLE
`ChromaDocumentStore` search raise error when document has no metadata

### ISSUE THREAD

**Issue by Guest400123064** [deepset-ai/haystack-core-integrations#668]
**Describe the bug**
In `ChromaDocumentStore._query_result_to_documents` method, line 375, the method tries to convert from `chromadb metadatas` to Haystack document metadata. It checks if the returned result has any metadata by `result.get("metadatas")`. This does not actually check if there is any metadata because the returned value will be a nested list, which is always not `None`. Then on line 376, if the metadata is actually empty, the second subscription will break.

**To Reproduce**
Simply create a document store with no-metadata documents and try to call `ChromaDocumentStore.search(["test query text"], 1)`. Commenting out the code snippet mentioned above should avoid error (but no metadata in returned documents)

**Describe your environment (please complete the following information):**
 - OS: MacOS
 - Haystack version: 2.0.1
 - Integration version: N/A, but as of April 16th 2024, the code on `main` branch is still causing the reported problem; should be tagged `chroma-v0.15.0`

**Comment by anakin87** [comment]
related to #462 (maybe a dupicate)

**Comment by Guest400123064** [comment]
Got it, yea, I think this is indeed a duplicate

**Comment by anakin87** [comment]
Closing as it is a duplicate.
