### ISSUE TITLE
Retrievers: should `document_store` be a private attribute?

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#69]
- Retrievers of `InMemoryDocumentStore` (`InMemoryBM25Retriever`...) have the attribute `document_store`

- Retrievers of Elasticsearch and Opensearch Document Store have the attribute `_document_store`

We should probably agree on a consistent approach,
so that for example `pipeline.get_component("retriever").document_store` always works.

@silvanocerza

**Comment by silvanocerza** [comment]
Yeah, doesn't make much sense for the Document Store to be public. Also if you created an instance of that Component I would expect you must have also built the Document Store it's using.

**Comment by masci** [comment]
What if I'm reading a pipeline from Yaml? I can still get the retriever with `pipeline.get_component("retriever")` but how do I access the document store?

**Comment by silvanocerza** [comment]
Good point, that indeed could be a use case. 🤔

**Comment by masci** [comment]
Let's agree that yes, it's ok to expose the document store instance and close this issue.

I'm not sure we should enforce a convention right now, it's an easy fix and we can patch integrations as we need it, but in case you want to schedule some work to uniform the existing document stores, please open another issue with a checklist of what should be done.
