### ISSUE TITLE
Add `source_tag` attribute to PineconeDocumentStore

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-core-integrations#715]
🚫 This is blocked by #223

We need to add `source_tag` to `PineconeDocumentStore` and set it as "haystack" to track this integration. See relevant [docs](https://pinecone-2-partner-integration-guide.mintlify.app/integrations/build-integration/attribute-api-activity) for more information about the field.

This is not possible right now as it requires `pinecone-client` to be `v3.2.1+`. Current version is `pinecone-client<3` -> The issue for this upgrade: #223

**Comment by mmurraysans** [comment]
Hi All,

I took a pass at updating this to the new client in #756
