### ISSUE TITLE
Pgvector - add usage example of Keyword Retriever to the integration page

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#726]
The integration page should be updated with a simple example showing the feature. -> https://github.com/deepset-ai/haystack-integrations/blob/main/integrations/pgvector-documentstore.md

Resources to take inspiration:
- [`PgvectorKeywordRetriever` docstring](https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/pgvector/src/haystack_integrations/components/retrievers/pgvector/keyword_retriever.py#L22)
- docs (WIP)

**Comment by jlonge4** [comment]
@anakin87 https://github.com/deepset-ai/haystack-integrations/pull/229
