### ISSUE TITLE
Pgvector - add examples of Keyword Retriever usage

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#727]
One or more usage examples should be added to this repo: https://github.com/deepset-ai/haystack-core-integrations/tree/main/integrations/pgvector/examples

I'm thinking about two possible examples in two different python files:
- `PgvectorKeywordRetriever` in a pipeline, similar to what we have done for the Embedding Retriever: https://github.com/deepset-ai/haystack-core-integrations/blob/main/integrations/pgvector/examples/embedding_retrieval.py
- combining `PgvectorKeywordRetriever` with `PgvectorEmbeddingRetriever`
  - similar to https://docs.haystack.deepset.ai/docs/documentjoiner#in-a-pipeline
  - also [the hybrid retrieval tutorial](https://haystack.deepset.ai/tutorials/33_hybrid_retrieval) is a good inspiration

**Comment by AnushreeBannadabhavi** [comment]
I can take this up if no one is working on it!

**Comment by anakin87** [comment]
Done in #738
