### ISSUE TITLE
Optimise LangfuseTracer - move flush to separate thread

### ISSUE THREAD

**Issue by Redna** [deepset-ai/haystack-core-integrations#782]
**Is your feature request related to a problem? Please describe.**
Currently the Langfuse integration is very slow when content tracing is enabled, even for a local Langfuse deployment. 
The problem is that the `trace` method defined in `haystack_integrations.tracing.langfuse.LangfuseTracer` is calling the `flush`method of the tracer. This blocks the entire Thread until the data has been pushed. As it is executed before and after each component this slows down the execution dramatically. 

From my experience adding Langfuse causes a slow down of around 3 to 5 times the normal execution time. 

**Describe the solution you'd like**

1. move the flush method to a separate Tread: 
     threading.Thread(target=self._tracer.flush, daemon=True)

**Describe alternatives you've considered**
make "force_flush" optional to enable this feature for short living applications (Lambda functions) and leave open to the developer to flush the data before application shutdown.

**Comment by touhi99** [comment]
+1 

also experiencing the issue with langfuse
