### ISSUE TITLE
OllamaChatGenerator return error in 'streaming_callback' argument

### ISSUE THREAD

**Issue by NILICK** [deepset-ai/haystack-core-integrations#791]
**Describe the bug**
Based on [this document](https://docs.haystack.deepset.ai/v2.0/reference/integrations-ollama#ollamachatgenerator__init__), I can use `streaming_callback` as argument in OllamaChatGenerator.

My code:
```
from haystack.dataclasses import ChatMessage
from haystack_integrations.components.generators.ollama import OllamaChatGenerator
from haystack.components.generators.utils import print_streaming_chunk

generator = OllamaChatGenerator(model="phi3",
                                url = "http://localhost:11434/api/chat",
                                streaming_callback = print_streaming_chunk,
                                generation_kwargs={
                                    "num_predict": 100,
                                    "temperature": 0.9,
                                    },
                                )

messages = [ChatMessage.from_system("\nYou are a helpful, respectful and honest assistant"),
ChatMessage.from_user("What's Natural Language Processing?")]

print(generator.run(messages=messages))
```
But it return error

**Error message**

TypeError: OllamaChatGenerator.__init__() got an unexpected keyword argument 'streaming_callback'

**System:**
 - OS: Ubuntu 
 - Haystack version (commit or version number): 2.2.1

**Comment by anakin87** [comment]
Hello!

I have tried your code with the latest version of `ollama-haystack` (0.0.7) and works for me.

Please try reinstalling the latest version (`pip install -U ollama-haystack`)  and let us know.
