### ISSUE TITLE
Llama 3 in AWS Bedrock Integration

### ISSUE THREAD

**Issue by jsigman** [deepset-ai/haystack-core-integrations#800]
**Is your feature request related to a problem? Please describe.**
Can you support using Llama3 models in `AmazonBedrockChatGenerator`?

**Describe alternatives you've considered**
It could be coded up from scratch, but I think supporting most Bedrock models is part of the long-term strategy of this package.

**Comment by anakin87** [comment]
done in #809

**Comment by jsigman** [comment]
Thank you!
