### ISSUE TITLE
Document `LlamaCppChatGenerator`

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#807]
`LlamaCppChatGenerator` was introduced in #723 but it was never documented.

**Comment by lbux** [comment]
Given that I implemented it, I can at least add a README. I'm unsure if/how I could add a proper documentation page on the docs site as there is only an option to suggest changes to an existing page.

**Comment by anakin87** [comment]
Hey, @lbux! Currently, the process of adding docs for new components is manually handled. We hope to improve it in the future...

In the meantime, if you create a markdown draft and add it to this issue, we can then take care of refining and publishing it.

Similar examples: [LlamaCppGenerator](https://docs.haystack.deepset.ai/edit/llamacppgenerator), [OllamaChatGenerator](https://docs.haystack.deepset.ai/edit/ollamachatgenerator)

I also attach the markdown file for the LlamaCppGenerator, to help you get started:
[llamacppgenerator.md](https://github.com/user-attachments/files/15984157/llamacppgenerator.md).

What do you think? Let us know if you want to take care of it... :blue_heart:

**Comment by lbux** [comment]
Hello, @anakin87. Please see the updated file. I kept it very similar to the regular generator but added small bits that correspond to the additional options available for users (chat_format, json constraining, function calling, etc.). The examples have also been updated and ensured to be working with the exception of the "Using in a Pipeline" section which will work when https://github.com/deepset-ai/haystack/pull/7897 is merged
[llamacppchatgenerator.md](https://github.com/user-attachments/files/16021533/llamacppchatgenerator.md)

**Comment by anakin87** [comment]
@lbux thank you!

@dfokina coud you please review the markdown and create a new documentation page for `LlamaCppChatGenerator`?

**Comment by dfokina** [comment]
Thank you for the draft @lbux ! The doc page is live: https://docs.haystack.deepset.ai/docs/llamacppchatgenerator
