### ISSUE TITLE
Adding configurable index names 

### ISSUE THREAD

**Issue by LTMenezes** [deepset-ai/haystack-core-integrations#812]
**Is your feature request related to a problem? Please describe.**
Yes, currently the index names (more precisely HNSW_INDEX_NAME and KEYWORD_INDEX_NAME) are not configurable, this means that you cannot create two or more document_stores tables on the same postgres schema, since you cannot have two indexes with the same name.

**Describe the solution you'd like**
I'd like for the index name to be configurable and to the index creation to be optional, just as the recreation of the table is also optional under the flag 'recreate_table'.

**Describe alternatives you've considered**
I've considered changing the index names on the tables manually, but because the index is always checked to exist by name it's impossible to workaround this.

**Additional context**
I'd be happy to make a PR for this myself, just want to make sure that I'm not missing anything before working on this.

**Comment by anakin87** [comment]
Hello! Thanks for discussing this idea...
We would be happy if you could contribute.

I agree that the index names should be configurable (we can leave the current names as default names).

Could you better explain why you would like the index creation to be optional and how it would differ from the current implementation?

**Comment by anakin87** [comment]
Perfect! Feel free to start by making index names configurable.
Then we could explore the other aspect in a later PR.
