### ISSUE TITLE
AmazonBedrockGenerator unable to return output

### ISSUE THREAD

**Issue by sahil-invent** [deepset-ai/haystack-core-integrations#832]
**Describe the bug**
The Amazon Bedrock Generator and Chat Generator produces an error when running inference. I think its failing to invoke the model.

**To Reproduce**
To reproduce the error:
After installing haystack-ai and importing the Amazon Bedrock Generator.
Initialise AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION as global variables.
AWS_DEFAULT_REGION is set to 'eu-west-2'

Run:
generator = AmazonBedrockGenerator(model="anthropic.claude-3-sonnet-20240229-v1:0")
result = generator.run("Who is the best American actor?")
for reply in result["replies"]:
    print(reply)

Error produced:
TypeError: sequence item 0: expected str instance, NoneType found 
from Line 208 in .haystack_integrations/components/generators/amazon_bedrock/generator.py

**Describe your environment (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Haystack version: haystack-ai 2.2.1
 - Integration version: amazon-bedrock-haystack 0.9.0

Happy to add more details if needed.

**Comment by anakin87** [comment]
This code works for me.

```python
import os
from haystack_integrations.components.generators.amazon_bedrock import AmazonBedrockGenerator


os.environ["AWS_ACCESS_KEY_ID"]="..."
os.environ["AWS_SECRET_ACCESS_KEY"]="..."
os.environ["AWS_DEFAULT_REGION"]="eu-west-3"

generator = AmazonBedrockGenerator(model="anthropic.claude-3-sonnet-20240229-v1:0")
result = generator.run("Who is the best American actor?")
print(result)
```

Please note that not all models are supported in all AWS regions. -> [Detailed information](https://docs.aws.amazon.com/bedrock/latest/userguide/models-regions.html)

**Comment by sahil-invent** [comment]
Apologies was typo in declaring the 'AWS_ACCESS_KEY_ID' where I didn't include the '_ID'. Thanks for your help!
