### ISSUE TITLE
Issue with converting Haystack filters to Qdrant style

### ISSUE THREAD

**Issue by ms130** [deepset-ai/haystack-core-integrations#846]
**Describe the bug**
I'm using the Qdrant document store integration with Haystack. I'm running a retrieval pipeline where I'd like to filter search results using metadata. I have created the filter in Haystack dictionary format, and this gets converted to Qdrant filter format when I run the pipeline and provide the filter dictionary to the retriever components.

The problem is the filter dictionary I'm using, which is a little complex, doesn't get converted properly to Qdrant format, some of the filters are completely absent from the Qdrant version. 

**To Reproduce**
Here is an example of the type of Haystack filter dictionary I'd like to convert:
```
filter = {
    "operator": "AND",
    "conditions": [
        {
            "field": "meta.file_name",
            "operator": "in",
            "value": [
                "file1",
                "file2"
            ]
        },
        {
            "operator": "OR",
            "conditions": [
                {
                    "field": "\"meta\".\"classification\".\"details\".\"category1\"",
                    "operator": ">=",
                    "value": 0.85
                },
                {
                    "field": "\"meta\".\"classification\".\"details\".\"category2\"",
                    "operator": ">=",
                    "value": 0.85
                }
            ]
        }
    ]
} 
```
If I convert this using `convert_filters_to_qdrant` the output is:
```
from haystack_integrations.document_stores.qdrant.filters import convert_filters_to_qdrant

qdrant_filter = convert_filters_to_qdrant(filter)
qdrant_filter = 
    "must": [
        {
            "should": [
                {
                    "key": "meta.file_name",
                    "match": {
                        "text": "file1"
                    }
                },
                {
                    "key": "meta.file_name",
                    "match": {
                        "text": "file2"
                    }
                }
            ]
        }
    ]
}
```
Here, the category1 and category2 filters are missing from the output, so my search results don't get filtered properly.

What I'd expect to see is the category filters to be present in the qdrant version output by `convert_filters_to_qdrant` and in a way that reflects the logic correctly in my original Haystack filter.

**Describe your environment**
 - OS: macOS Version 14.5
 - Haystack version: 2.1.0 
 - Integration version: qdrant-haystack version 3.5.0

**Comment by silvanocerza** [comment]
This indeed a bug in the conversion, though I'm wondering why are you writing the `field` like that? 🤔 

`meta.classification.details.category1` this seems more correct to me. It doesn't fix the bug though.

**Comment by ms130** [comment]
> This indeed a bug in the conversion, though I'm wondering why are you writing the field like that?

I wrote it this way to allow for categories containing multiple words with spaces. E.g. if `category1` was actually `"popular science"` using that formatting the filtering works. Comes from [this](https://github.com/qdrant/qdrant-client/issues/631#issuecomment-2129495120) response to an Issue I raised.
