### ISSUE TITLE
Langfuse not showing costs or input/output of components

### ISSUE THREAD

**Issue by mrm1001** [deepset-ai/haystack-core-integrations#871]
**Describe the bug**

There is a user on [discord](https://discord.com/channels/993534733298450452/1256702891172036608/1256702891172036608) who cannot see costs or input/outputs of components on Langfuse.

**To Reproduce**

```import os
from haystack import Pipeline
from haystack.components.builders import PromptBuilder
from haystack_integrations.components.generators.anthropic import AnthropicGenerator

from dotenv import load_dotenv

def make_pipeline():
    from haystack_integrations.components.connectors.langfuse import LangfuseConnector
    pipe = Pipeline()

    extract_prompt_builder = PromptBuilder(template=extract_question_prompt)
    extractor_llm = AnthropicGenerator(model="claude-3-haiku-20240307")

    pipe.add_component("tracer", LangfuseConnector("Test Logging"))
    pipe.add_component(instance=extract_prompt_builder, name="extract_prompt_builder")
    pipe.add_component(instance=extractor_llm, name="extractor_llm")

    pipe.connect("extract_prompt_builder", "extractor_llm")

    return pipe

if __name__ == "__main__":
    load_dotenv()
    print(os.getenv('LANGFUSE_SECRET_KEY'), os.getenv('LANGFUSE_PUBLIC_KEY'), os.getenv('LANGFUSE_HOST'), os.getenv('HAYSTACK_CONTENT_TRACING_ENABLED'))
    # os.environ['LANGFUSE_DEBUG'] = 'True'
    extract_question_prompt = "{{batch}} | How old is John?"
    pipe = make_pipeline()
    result = pipe.run(
        {"extract_prompt_builder": {"batch": "John is 34 years old"}}
    )
    print(result)
```

**Describe your environment (please complete the following information):**
 - Haystack version:
 - Integration version:

What the user sees on the Langfuse dashboard:

* No costs:
![image](https://github.com/deepset-ai/haystack-core-integrations/assets/7556409/89c466a4-96eb-44e5-9aa9-1ec9525f6523)

* No i/o:
![image](https://github.com/deepset-ai/haystack-core-integrations/assets/7556409/4fe574bd-315e-4124-a1ce-def47ac03b46)

* No i/o:
![image](https://github.com/deepset-ai/haystack-core-integrations/assets/7556409/22a2a3c7-88ea-4450-924e-8bb80b843a2e)

**Comment by anakin87** [comment]
This can be related to the fact that we only support OpenAI/Azure Generators in our integration.
https://github.com/deepset-ai/haystack-core-integrations/blob/52b0a1a59187c1b0001c2c07351438554e0788b1/integrations/langfuse/src/haystack_integrations/tracing/langfuse/tracer.py#L12

**Comment by mrm1001** [comment]
Ah right! Ok, I will close this issue and open a new feature request one then. Thanks!
