### ISSUE TITLE
Chroma-haystack 0.20.1 is not compatible with haystack 2.3.0

### ISSUE THREAD

**Issue by springrain** [deepset-ai/haystack-core-integrations#904]
**Describe the bug**
chroma-haystack 0.20.1 is not compatible with haystack 2.3.0.
```text
 raise ValueError(
ValueError: Expected metadata value to be a str, int, float or bool, got [{'doc_id': 'eaf05ac742e3e047b8293cc82333a04f3ba771c19f7450ef876950ae11b1f75f', 'range': (0, 252)}] which is a list
```

**Describe your environment (please complete the following information):**
 - OS: [e.g. iOS] Win11 
 - Haystack version: 2.3.0
 - Integration version: chroma-haystack 0.20.1

**Comment by anakin87** [comment]
Hello!
I ran the example and could not reproduce the error.

Can you add a reproducible code example that triggers the error?

**Comment by anakin87** [comment]
Ok, you are right. Thanks for reporting the bug!

## Minimal reproducible example
```python
from haystack.components.preprocessors import DocumentSplitter
from haystack import Document
from haystack_integrations.document_stores.chroma import ChromaDocumentStore


document_store = ChromaDocumentStore()

documents = [Document(content = "This is a test document to split "*10)]

document_splitter = DocumentSplitter(split_by="word", split_length=5, split_overlap=2)

splitted_docs=document_splitter.run(documents=documents)["documents"]

print(splitted_docs[0].meta)
# {'source_id': '7c1703594787e30800683d64673880811611051d4444f08d8619f8fba6ab1480', 'page_number': 1, 'split_id': 0, 'split_idx_start': 0,
# '_split_overlap': [{'doc_id': '187258e53ee90d2cf6f67f2e63e17d390c195b929b8721572e61c9e389a23e8d', 'range': (0, 13)}]}

document_store.write_documents(splitted_docs)
```

`ValueError: Expected metadata value to be a str, int, float or bool, got [{'doc_id': '187258e53ee90d2cf6f67f2e63e17d390c195b929b8721572e61c9e389a23e8d', 'range': (0, 13)}] which is a list`

## Debugging and potential solutions
In https://github.com/deepset-ai/haystack/pull/7933, we added the `_split_overlap` list to `meta`, but Chroma cannot handle lists in metadata.

One solution in `ChromaDocumentStore` might be to check the type of the single entry in `meta` before writing to Chroma and to discard the entry if not valid.

**Comment by springrain** [comment]
Okay, thanks, I'm currently using Haystack 2.2.4

**Comment by anakin87** [comment]
I reopened the issue because this is a bug we should fix.

**Comment by anakin87** [comment]
@springrain fixed and released a new version of `chroma-haystack`: https://pypi.org/project/chroma-haystack/0.21.1/
