### ISSUE TITLE
docs: improve docs for `UnstructuredFileConverter`

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#908]
While `UnstructuredFileConverter` is powerful and quite used by the community,
our current [docs](https://docs.haystack.deepset.ai/docs/unstructuredfileconverter) and [integration page](https://haystack.deepset.ai/integrations/unstructured-file-converter) are minimal.

I would like to expand the current docs
- specify/explain all the supported APIs: hosted - free and paid; local - via Docker (see also #169)
- better show that the converter supports passing a directory and automatically converting files within it
- better show some of the supported file types

**Comment by dfokina** [comment]
@anakin87 When you have a chance to get to this issue, I have created a [Notion page](https://www.notion.so/deepsetai/UnstructuredFileConverter-e15551e2f9974c359e0ec314e4b2c79f) with some notes.

**Comment by anakin87** [comment]
@dfokina thanks!
Done.

When the docs are updated, I can take care of updating the integration page similarly...

**Comment by dfokina** [comment]
Updated the docs: https://docs.haystack.deepset.ai/docs/unstructuredfileconverter

**Comment by anakin87** [comment]
update integration page: https://haystack.deepset.ai/integrations/unstructured-file-converter
