### ISSUE TITLE
Hybrid Retriever for Chroma

### ISSUE THREAD

**Issue by ss2342** [deepset-ai/haystack-core-integrations#933]
Is there a Hybrid Retriever Implementation of Chroma within Haystack2.0? Or a ChromaB25Retriever that could be then used to construct a hybrid retriever with Chroma? Thanks!

**Comment by anakin87** [comment]
After some investigation, I found that Chroma does not support keyword search.

It only supports filtering the results of embedding retrieval using text.  See the [docs](https://docs.trychroma.com/guides#querying-a-collection).

So, if you are interested in true hybrid retrieval, I suggest you take a look at other DBs such as Weaviate, Qdrant, Elasticsearch, OpenSearch...
