### ISSUE TITLE
VertexAIGeminiChatGenerator streaming_callback implementation (or streaming response)

### ISSUE THREAD

**Issue by sataycat** [deepset-ai/haystack-core-integrations#936]
**Is your feature request related to a problem? Please describe.**
Similar to this ticket, the VertexAIGeminiChatGenerator does have streaming_callback implementation, even though the underlying `GenerativeModel` does support `stream=True`
https://github.com/deepset-ai/haystack/issues/7836

The underlying model supports an iterable chat response
https://github.com/googleapis/python-aiplatform/blob/main/vertexai/generative_models/_generative_models.py#L522

**Describe the solution you'd like**
Similar to this
https://github.com/deepset-ai/haystack/pull/8054, by @Amnah199 :)

**Comment by TuanaCelik** [comment]
I think these are pretty much the same but for Google AI generators @julian-risch and @Amnah199 = https://github.com/deepset-ai/haystack-core-integrations/issues/1002
