### ISSUE TITLE
Llama.cpp tests failing

### ISSUE THREAD

**Issue by anakin87** [deepset-ai/haystack-core-integrations#938]
**Describe the bug**
https://github.com/deepset-ai/haystack-core-integrations/actions/runs/10189627850/job/28188014440
> Segmentation fault (core dumped)

The bug was introduced in `llama-cpp-python==0.2.84`

related issues/PRs:
https://github.com/abetlen/llama-cpp-python/issues/1636
https://github.com/abetlen/llama-cpp-python/pull/1637

We can wait for the bug to be fixed or pin the dependency to a working version...

**Comment by Amnah199** [comment]
Maybe pin the dependency? I need to push a small change for DynamicPromptBuilder in example file and failing tests are blocking my PR.
