### ISSUE TITLE
Bedrock Converse API integration

### ISSUE THREAD

**Issue by FloRul** [deepset-ai/haystack-core-integrations#977]
# Integrate AWS Bedrock Converse API into Haystack

## Background
AWS Bedrock released earlier this year their new converse API that aims to standardize their api calls to their models.

## Objective
Integrate the AWS Bedrock Converse API into the Haystack integration library to allow users to leverage AWS Bedrock converse within their Haystack pipelines, paving the way potentially for easier agent development and multimodal integration.

## Proposed Features
1. Add a new `BedrockConversationGenerator` node in Haystack integrations.
2. Support easy tool calling with some new classes to ease the process of tools definition and calling.
3. Support streaming responses from the Bedrock Converse API.
4. Implement error handling and retries for API calls.

## Implementation Details
- Use the AWS SDK for Python (Boto3) to interact with the Bedrock Converse API.
- Follow Haystack's node implementation guidelines for consistency.

## Resources
- [AWS Bedrock Converse Documentation](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html)
- [Model/Features compatibility](https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html)

### Alternatives
This could also be a feature for the existing AmazonBedrock generators instead of a new one.

**Comment by FloRul** [comment]
Currently working on it

**Comment by lambda-science** [comment]
> Currently working on it

Following on this, it will help a lot with tool use across all AWS Bedrock models with this unified API

**Comment by julian-risch** [comment]
@vblagoje Related issue: https://github.com/deepset-ai/haystack-core-integrations/issues/1229

**Comment by vblagoje** [comment]
Completed with https://github.com/deepset-ai/haystack-core-integrations/pull/1219
https://pypi.org/project/amazon-bedrock-haystack/ v2.0.0 released
