### ISSUE TITLE
docs: Update Bedrock documentation to show streaming example

### ISSUE THREAD

**Issue by Amnah199** [deepset-ai/haystack-core-integrations#979]
**Is your feature request related to a problem? Please describe.**
The `BedrockGenerator` now supports `streaming_callback`, similar to the `OpenAIGenerator`. After its release, it would be beneficial to include an example of 'Streaming' in the documentation to demonstrate its usage.

**Describe the solution you'd like**
Add a separate example code for streaming, similar to the example provided for the `OpenAIGenerator` in the documentation:
[OpenAIGenerator Example](https://docs.haystack.deepset.ai/docs/openaigenerator).

**Describe alternatives you've considered**
NA
**Additional context**
NA

**Comment by dfokina** [comment]
I attempted to make the information about streaming support more visible to users without manually rewriting examples for each component page:
- Added a column to the [Generators overview table](https://docs.haystack.deepset.ai/docs/generators).
- Explained streaming support in [Choosing the Right Generator](https://docs.haystack.deepset.ai/docs/choosing-the-right-generator#streaming-support) guide with a generic example.
- Added a reusable snippet called ["Streaming"](https://docs.haystack.deepset.ai/docs/amazonbedrockchatgenerator#streaming) to the pages of Generators that support streaming.

This way, all three pages are somewhat interconnected, so users should be able to easily find this information.

@Amnah199 @julian-risch  please take a look if this makes sense before I close this :)
